version: '3.8'

services:
  db:
    image: postgres
    container_name: psql_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: compose
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - dbnet

volumes:
  db_data:

networks:
  dbnet:


